steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/ans-dashboard:$SHORT_SHA
      - --build-arg
      - VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg
      - VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
      - --build-arg
      - VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}
      - --build-arg
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}
      - --build-arg
      - VITE_FIREBASE_MEASUREMENT_ID=${_VITE_FIREBASE_MEASUREMENT_ID}
      - --build-arg
      - VITE_DATASET_VIEW=${_VITE_DATASET_VIEW}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/ans-dashboard:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - gcr.io/$PROJECT_ID/ans-dashboard:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - ${_RUN_SERVICE_ACCOUNT}
      - --cpu
      - '1'
      - --memory
      - '1Gi'
      - --concurrency
      - '1'
      - --max-instances
      - '3'
      - --timeout
      - '300s'
      - --set-env-vars
      - NODE_ENV=production,SERVE_STATIC=true,BQ_PROJECT_ID=${_BQ_PROJECT_ID},BQ_DATASET=${_BQ_DATASET},BQ_DATASET_VIEW=${_BQ_DATASET_VIEW},BQ_LOCATION=${_BQ_LOCATION},OPENAI_MODEL=${_OPENAI_MODEL},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}
      - --set-secrets
      - OPENAI_API_KEY=OPENAI_API_KEY:latest

images:
  - gcr.io/$PROJECT_ID/ans-dashboard:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: ans-dashboard
  _REGION: us-central1
  _RUN_SERVICE_ACCOUNT: ans-dashboard-run@bigdata-467917.iam.gserviceaccount.com
  _BQ_PROJECT_ID: bigdata-467917
  _BQ_DATASET: datalake_ans
  _BQ_DATASET_VIEW: indicadores_curados_snapshot
  _BQ_LOCATION: US
  _OPENAI_MODEL: gpt-5-mini
  _FIREBASE_PROJECT_ID: bigdata-467917
  _VITE_FIREBASE_API_KEY: "AIzaSyDGszlkE1Jo_guXMs_QUGow8EK4pYgrp4Y"
  _VITE_FIREBASE_AUTH_DOMAIN: "bigdata-467917.firebaseapp.com"
  _VITE_FIREBASE_PROJECT_ID: "bigdata-467917"
  _VITE_FIREBASE_APP_ID: "1:565810349046:web:51a21f3b1609ca39597dd7"
  _VITE_FIREBASE_STORAGE_BUCKET: "bigdata-467917.firebasestorage.app"
  _VITE_FIREBASE_MESSAGING_SENDER_ID: "565810349046"
  _VITE_FIREBASE_MEASUREMENT_ID: "G-12MS8R4KQS"
  _VITE_DATASET_VIEW: "indicadores_curados_snapshot"
