CREATE OR REPLACE VIEW public.indicadores_curados AS
WITH base AS (
  SELECT
    reg_ans,
    MIN(operadora) FILTER (WHERE operadora IS NOT NULL) AS nome_operadora,
    MIN(modalidade) FILTER (WHERE modalidade IS NOT NULL) AS modalidade,
    bool_or(uniodonto) AS uniodonto,
    bool_or(ativa) AS ativa,
    MAX(beneficiarios) AS qt_beneficiarios,
    ano,
    trimestre,
    MAX(periodo) AS periodo_data,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '3') AS vr_receitas,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '4') AS vr_despesas,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '311') AS vr_contraprestacoes,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '3111') AS vr_contraprestacoes_efetivas,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '311121') AS vr_contraprestacoes_pre,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '3117') AS vr_corresponsabilidade_cedida,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '1231') AS vr_creditos_operacoes_saude,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '41') AS vr_eventos_liquidos,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '2111') AS vr_eventos_a_liquidar,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '43') AS vr_desp_comerciais,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '464119113') AS vr_desp_comerciais_promocoes,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '46') AS vr_desp_administrativas,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '44') AS vr_outras_desp_oper,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '47') AS vr_desp_tributos,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '35') AS vr_receitas_fin,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '36') AS vr_receitas_patrimoniais,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '45') AS vr_despesas_fin,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '33') AS vr_outras_receitas_operacionais,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '12') AS vr_ativo_circulante,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '13') AS vr_ativo_permanente,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '21') AS vr_passivo_circulante,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '23') AS vr_passivo_nao_circulante,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '25') AS vr_patrimonio_liquido,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '31') AS vr_ativos_garantidores,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '32') AS vr_provisoes_tecnicas,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '2521') AS vr_pl_ajustado,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '2522') AS vr_margem_solvencia_exigida,
    SUM(COALESCE(vl_saldo_final, 0)) FILTER (WHERE cd_conta_contabil = '61') AS vr_conta_61
  FROM public.demonstracoes_contabeis
  GROUP BY reg_ans, ano, trimestre
), lagged AS (
  SELECT
    base.*,
    LAG(vr_eventos_liquidos) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre) AS prev_vr_eventos_liquidos,
    LAG(vr_corresponsabilidade_cedida) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre) AS prev_vr_corresponsabilidade_cedida,
    LAG(vr_contraprestacoes) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre) AS prev_vr_contraprestacoes,
    LAG(vr_provisoes_tecnicas) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre) AS prev_vr_provisoes_tecnicas,
    COALESCE(vr_eventos_liquidos, 0) - COALESCE(LAG(vr_eventos_liquidos) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre), 0) AS delta_vr_eventos_liquidos,
    COALESCE(vr_corresponsabilidade_cedida, 0) - COALESCE(LAG(vr_corresponsabilidade_cedida) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre), 0) AS delta_vr_corresponsabilidade_cedida,
    COALESCE(vr_contraprestacoes, 0) - COALESCE(LAG(vr_contraprestacoes) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre), 0) AS delta_vr_contraprestacoes,
    COALESCE(vr_provisoes_tecnicas, 0) - COALESCE(LAG(vr_provisoes_tecnicas) OVER (PARTITION BY reg_ans, ano ORDER BY trimestre), 0) AS delta_vr_provisoes_tecnicas
  FROM base
)
SELECT
  lagged.reg_ans,
  lagged.nome_operadora,
  lagged.modalidade,
  lagged.uniodonto,
  lagged.ativa,
  lagged.qt_beneficiarios,
  meta.porte,
  lagged.ano,
  lagged.trimestre,
  lagged.periodo_data AS periodo_raw,
  (lagged.ano * 10 + lagged.trimestre) AS periodo_id,
  CONCAT(lagged.ano, 'T', lagged.trimestre) AS periodo,
  ROW_NUMBER() OVER (PARTITION BY lagged.reg_ans, lagged.ano ORDER BY lagged.trimestre DESC) AS trimestre_rank,
  lagged.vr_receitas,
  lagged.vr_despesas,
  lagged.vr_contraprestacoes,
  lagged.vr_contraprestacoes_efetivas,
  lagged.vr_contraprestacoes_pre,
  lagged.vr_corresponsabilidade_cedida,
  lagged.vr_creditos_operacoes_saude,
  lagged.vr_eventos_liquidos,
  lagged.vr_eventos_a_liquidar,
  lagged.vr_desp_comerciais,
  lagged.vr_desp_comerciais_promocoes,
  lagged.vr_desp_administrativas,
  lagged.vr_outras_desp_oper,
  lagged.vr_desp_tributos,
  lagged.vr_receitas_fin,
  lagged.vr_receitas_patrimoniais,
  lagged.vr_despesas_fin,
  lagged.vr_outras_receitas_operacionais,
  lagged.vr_ativo_circulante,
  lagged.vr_ativo_permanente,
  lagged.vr_passivo_circulante,
  lagged.vr_passivo_nao_circulante,
  lagged.vr_patrimonio_liquido,
  lagged.vr_ativos_garantidores,
  lagged.vr_provisoes_tecnicas,
  lagged.vr_pl_ajustado,
  lagged.vr_margem_solvencia_exigida,
  lagged.vr_conta_61,
  COALESCE(lagged.vr_receitas_fin, 0) - COALESCE(lagged.vr_despesas_fin, 0) AS resultado_financeiro,
  COALESCE(lagged.vr_receitas, 0) - COALESCE(lagged.vr_despesas, 0) AS resultado_liquido,
  COALESCE(lagged.vr_receitas, 0) - COALESCE(lagged.vr_despesas, 0) AS resultado_liquido_calculado,
  COALESCE(lagged.vr_receitas, 0) - COALESCE(lagged.vr_despesas, 0) - COALESCE(lagged.vr_conta_61, 0) AS resultado_liquido_final_ans,
  COALESCE(lagged.vr_receitas, 0) - COALESCE(lagged.vr_despesas, 0) AS resultado_liquido_informado,
  lagged.prev_vr_eventos_liquidos,
  lagged.prev_vr_corresponsabilidade_cedida,
  lagged.prev_vr_contraprestacoes,
  lagged.prev_vr_provisoes_tecnicas,
  lagged.delta_vr_eventos_liquidos,
  lagged.delta_vr_corresponsabilidade_cedida,
  lagged.delta_vr_contraprestacoes,
  lagged.delta_vr_provisoes_tecnicas
FROM lagged
LEFT JOIN public.operadoras_metadata meta ON meta.reg_ans = lagged.reg_ans;
